apiVersion: v1
kind: Service
metadata:
  name: oci-load-balancing-service
  labels:
    app: oci-load-balancing-service
  annotations:
    # Smallest possible LB shape to avoid issues with OCI quotas
    service.beta.kubernetes.io/oci-load-balancer-shape: 10Mbps
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: seat-booking-service