apiVersion: v1
kind: Service
metadata:
  name: oci-load-balancing-service
  labels:
    app: oci-load-balancing-service
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: 10Mbps
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: oci-load-balancing-service