apiVersion: v1
kind: ConfigMap
metadata:
  name: coordinator-envs
data:
  CONFIG_FILE: tcs.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcs-config
data:
  tcs.yaml: |
    tmmAppName: tcs
    tmmConfiguration:
      listenAddr: 0.0.0.0:8080
      internalAddr: http://127.0.0.1:8080
      externalUrl: http://lra-coordinator:8080
      xaCoordinator:
        enabled: false
      lraCoordinator:
        enabled: true
      tccCoordinator:
        enabled: false
      maxRetryCount: 10
      minRetryInterval: 1000
      maxRetryInterval: 10000
      logging:
        httpTraceEnabled: true
        level: debug
        devMode: true
      storage:
        type: memory
      authentication:
        enabled: false
      authorization:
        enabled: false
      serveTLS:
        enabled: false
      narayanaLraCompatibilityMode:
        enabled: true
---
kind: Service
apiVersion: v1
metadata:
  name: lra-coordinator
  labels:
    app: lra-coordinator
spec:
  type: NodePort
  selector:
    app: lra-coordinator
  ports:
  - port: 8080
    targetPort: 8080
    name: 8080-tcp
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lra-coordinator
  labels:
    app: lra-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lra-coordinator
  template:
    metadata:
      labels:
        app: lra-coordinator
    spec:
      containers:
        - name: lra-coordinator
          # Oracle MicroTx (Oracle Transaction Manager for Microservices)
          image: container-registry.oracle.com/database/otmm:22.3
          imagePullPolicy: IfNotPresent
          workingDir: /app/config
          envFrom:
            - configMapRef:
                name: coordinator-envs
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
          ports:
            - containerPort: 8080
      volumes:
        - name: config-volume
          configMap:
            name: tcs-config
