kind: Service
apiVersion: v1
metadata:
  name: booking-db
  labels:
    app: booking-db
spec:
  type: NodePort
  selector:
    app: booking-db
  ports:
  - port: 5432
    targetPort: 5432
    name: 5432-tcp
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-db
  labels:
    app: booking-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-db
  template:
    metadata:
      labels:
        app: booking-db
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: booking-db
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: "booking-db"
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "pass"
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
          readinessProbe:
            exec:
              command: ["psql", "-w", "-U", "user", "-d", "booking-db", "-c", "SELECT 1"]
            initialDelaySeconds: 5
            timeoutSeconds: 15
          livenessProbe:
            exec:
              command: ["psql", "-w", "-U", "user", "-d", "booking-db", "-c", "SELECT 1"]
            initialDelaySeconds: 20
            timeoutSeconds: 5
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory