kind: Service
apiVersion: v1
metadata:
  name: seat-booking-service
  labels:
    app: seat-booking-service
spec:
  type: NodePort
  selector:
    app: seat-booking-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: seat-booking-service
  labels:
    app: seat-booking-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seat-booking-service
      version: v1
  template:
    metadata:
      labels:
        app: seat-booking-service
        version: v1
    spec:
      containers:
        - name: seat-booking-service
          image: cinema-reservation/seat-booking-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080