kind: Service
apiVersion: v1
metadata:
  name: seat-booking-service
  labels:
    app: seat-booking-service
spec:
  type: NodePort
  selector:
    app: seat-booking-service
  ports:
  - port: 7001
    targetPort: 7001
    name: http
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: seat-booking-service
  labels:
    app: seat-booking-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seat-booking-service
      version: v1
  template:
    metadata:
      labels:
        app: seat-booking-service
        version: v1
    spec:
      containers:
        - name: seat-booking-service
          image: cinema-reservation/seat-booking-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7001
      initContainers:
        - name: wait-for-db
          image: curlimages/curl:latest
          command: [ "/bin/sh","-c" ]
          args: [ "while [[ $(kubectl get pods -l name=booking-db -o 'jsonpath={..status.conditions[?(@.type==\"Ready\")].status}') != \"True\" ]]; do echo 'waiting for pod' && sleep 1; done" ]